[package]
name = "rlget"
version = "0.0.1"
authors = ["jake@mccoy.engineer"]

[dependencies]
reqwest = "=0.9.13"
docopt = "1.1.0"
serde = "1.0.91"
indicatif = "0.12.0"
http = "0.1.15"

toml = "0.4"
serde_derive = "1.0.91"

[features]
content_comparing = []